[project]
name = "mcp-utp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.116.1",
    "fastmcp==2.12.3",
    "mcp>=1.14.1",
    "requests>=2.32.5",
    "uvicorn>=0.35.0",
]
